-- MySQL Script generated by MySQL Workbench
-- ven. 20 sept. 2019 12:40:10 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cardgame
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cardgame` ;

-- -----------------------------------------------------
-- Schema cardgame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cardgame` ;
USE `cardgame` ;

CREATE TABLE IF NOT EXISTS `cardgame`.`cards` (
  `idcard` INT NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  `weight` INT NOT NULL,
  `figure` INT NULL,
  `colors_id` INT NOT NULL,
  PRIMARY KEY (`idcard`),
  INDEX `fk_cards_colors_idx` (`colors_id` ASC),
  CONSTRAINT `fk_cards_colors`
    FOREIGN KEY (`colors_id`)
    REFERENCES `cardgame`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Playing cards';


-- -----------------------------------------------------
-- Table `cardgame`.`colors`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `cardgame`.`colors` (
  `id` INT NOT NULL,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = 'color name (and weight)';

INSERT INTO cardgame.colors ( id, name) VALUES ( '0', 'Pique');
INSERT INTO cardgame.colors ( id, name) VALUES ( '1', 'Coeur');
INSERT INTO cardgame.colors ( id, name) VALUES ( '2', 'Trèfle');
INSERT INTO cardgame.colors ( id, name) VALUES ( '3', 'Carreau');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
